In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [5]:
arr[9]

9

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

### Broadcasting

Numpy arrays will differ from normal python list because of their ability to broadcast

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:5] = 99

In [11]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [12]:
slicearr = arr[0:6]
slicearr

array([99, 99, 99, 99, 99,  5])

In [13]:
slicearr[:] = 100
slicearr

array([100, 100, 100, 100, 100, 100])

In [14]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [15]:
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### Selection

In [16]:
arr = np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
barr = arr > 4

In [19]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [20]:
arr[barr]

array([ 5,  6,  7,  8,  9, 10])

## shallow and deep copy

In [21]:
xx = [[1,2,3],[4,5,6],[7,8,9]]
yy = list(xx) # Making a shallow copy

The above operation is shallow copy

yy will be a new and independent object with same content as xx.

In [22]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
xx.append(['new list nested'])

In [25]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9], ['new list nested']]

In [26]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
xx[1][0] = 99999

In [28]:
xx

[[1, 2, 3], [99999, 5, 6], [7, 8, 9], ['new list nested']]

In [29]:
yy

[[1, 2, 3], [99999, 5, 6], [7, 8, 9]]

### Deep Copy

In [30]:
import copy

In [31]:
xxd =[[1,2,3],[4,5,6],[7,8,9]]
zz = copy.deepcopy(xxd)


In [32]:
xxd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [33]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [34]:
xxd[1][0] ='XXXXX'

In [35]:
xxd

[[1, 2, 3], ['XXXXX', 5, 6], [7, 8, 9]]

In [36]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#Iteration in Numpy


In [58]:
arr = np.array([[[1, 2, 4], [3, 4, 8] ], [[5, 6, 9], [7, 8, 89]] , [[10, 23, 44], [34, 44, 83]]])
# for x in arr:
#   for y in x:
#     for z in y:
#       print(z)

print(arr.shape)
print(arr[:][:][::2])
# for x in np.nditer():
#   print(x)

(3, 2, 3)
[[[ 1  2  4]
  [ 3  4  8]]

 [[10 23 44]
  [34 44 83]]]


In [40]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


In [42]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[8, 9, 88, 90]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7
8
88


In [43]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


#Joining

In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [61]:
arr1 = np.array([[1, 2], [3, 4], [9, 10]])

arr2 = np.array([[5, 6], [7, 8], [11, 23]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 11 23]]


In [62]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [63]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [67]:
arr1 = np.array([[1, 2, 3],[ 8, 87, 65]])

arr2 = np.array([[4, 5, 6], [64, 45, 34]])

arr = np.vstack((arr1, arr2))

print(arr)


[[ 1  2  3]
 [ 8 87 65]
 [ 4  5  6]
 [64 45 34]]


In [69]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)
print(arr.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


#Filter

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = (arr % 2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr = arr % 3

print(arr)

filter_arr = (arr > 5)


arr = arr / 2

print(arr)

filter_arr = (arr > 2) & (arr < 5) 


newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[1 2 0 1 2 0 1]
[0.5 1.  0.  0.5 1.  0.  0.5]
[False False False False False False False]
[]
