## Numpy

<img src='https://numpy.org/_static/numpy_logo.png'>

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

https://numpy.org/


### Installation

pip install numpy

In [ ]:
!pip install numpy

#### Using numpy

In [2]:
import numpy as np # np is just an alias

#### Numpy Arrays

Two forms of numpy arrays:

* Vectors - 1-Dimensional
* Matrices - 2-Dimensional

### Creating numpy arrays

* From Python List

In [3]:
lst = [1,2,3,4,5]

lst

[1, 2, 3, 4, 5]

In [4]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in methods for numpy array

#### arange : Returns evenly spaced values within a given interval

In [7]:
lst = [x for x in range(0,10)]
print('python ' , lst)


print('nump ' , np.arange(0,10))

python  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
nump  [0 1 2 3 4 5 6 7 8 9]


In [8]:
lst = [x for x in range(0,10,2)]
print('python ' , lst)


print('nump ' , np.arange(0,10,2))

python  [0, 2, 4, 6, 8]
nump  [0 2 4 6 8]


#### zeros and ones
Generate arrays of zeros and ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### linspace
Returns evenly spaced numbers over a specified interval

In [17]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

#### eye
Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random

Numpy has lots of ways to create random number arrays

* rand
* randn
* randint

#### rand
Create and array of the given shape and populate it with the random samples from a uniform distribution over [0,1]

In [20]:
np.random.rand(10)

array([0.27642762, 0.69015905, 0.32005833, 0.5412815 , 0.30905583,
       0.94047679, 0.76034139, 0.23973476, 0.73781022, 0.25287335])

In [21]:
np.random.rand(5,5)

array([[0.80212169, 0.82442243, 0.61085757, 0.16925331, 0.55786904],
       [0.5147479 , 0.4837179 , 0.06090766, 0.21467588, 0.81489563],
       [0.43878288, 0.46159797, 0.73456678, 0.3332035 , 0.06198475],
       [0.0938418 , 0.31664451, 0.87827619, 0.58036278, 0.22679392],
       [0.26363638, 0.51565293, 0.68286055, 0.48721234, 0.66874349]])

#### randn
Creates a sample/samples from the standard normal distribution unlike rand which is uniform distribution

In [22]:
np.random.randn(4)

array([ 0.13763173, -0.74978079,  0.21787259,  0.6769874 ])

In [ ]:
np.random.randn(4,4)

array([[-1.24608359,  1.06017413, -0.55649202,  0.85525937],
       [-0.28757841,  0.76354165,  0.39220929, -0.68843735],
       [-0.58855344,  0.19332342, -0.05121918,  0.10866021],
       [-0.98193474, -0.86288538,  0.86468409, -1.88508482]])

#### randint
Returns random integers from low (included) to high (excluded)

In [26]:
np.random.randint(0,100)

7

In [27]:
np.random.randint(1,100,20)

array([38,  4, 83, 99, 52, 13, 57, 94, 92,  1, 86, 27,  7, 43, 31, 38, 13,
       79, 43, 81])

### Array attributes and methods

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([48, 17, 30, 10, 38,  7, 30, 43, 41, 13])

### Reshape

Returns an array containing same data but different shape

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min,argmax,argmin

Useful methods to find minimum and maximum values or index locations.

In [ ]:
ranarr

array([48, 17, 30, 10, 38,  7, 30, 43, 41, 13])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.min()

7

In [ ]:
ranarr.argmin()

5

### Shape
Shape is an attribute that arrays have

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Data type of object in array

In [ ]:
arr.dtype

dtype('int64')

# Great Job !!