In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [ ]:
arr[9]

9

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

### Broadcasting

Numpy arrays will differ from normal python list because of their ability to broadcast

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:5] = 99

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
slicearr = arr[0:6]
slicearr

array([99, 99, 99, 99, 99,  5])

In [ ]:
slicearr[:] = 100
slicearr

array([100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
arr_copy = arr.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### Selection

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
barr = arr > 4

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[barr]

array([ 5,  6,  7,  8,  9, 10])

## shallow and deep copy

In [ ]:
xx = [[1,2,3],[4,5,6],[7,8,9]]
yy = list(xx) # Making a shallow copy

The above operation is shallow copy

yy will be a new and independent object with same content as xx.

In [ ]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
xx.append(['new list nested'])

In [ ]:
xx

[[1, 2, 3], [4, 5, 6], [7, 8, 9], ['new list nested']]

In [ ]:
yy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
xx[1][0] = 99999

In [ ]:
xx

[[1, 2, 3], [99999, 5, 6], [7, 8, 9], ['new list nested']]

In [ ]:
yy

[[1, 2, 3], [99999, 5, 6], [7, 8, 9]]

### Deep Copy

In [ ]:
import copy

In [ ]:
xxd =[[1,2,3],[4,5,6],[7,8,9]]
zz = copy.deepcopy(xxd)


In [ ]:
xxd

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
xxd[1][0] ='XXXXX'

In [ ]:
xxd

[[1, 2, 3], ['XXXXX', 5, 6], [7, 8, 9]]

In [ ]:
zz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#Iteration in Numpy


In [20]:
arr = np.array([[[1, 2, 4], [3, 4, 8] ], [[5, 6, 9], [7, 8, 89]] , [[10, 23, 44], [34, 44, 83]]])
# for x in arr:
#   for y in x:
#     for z in y:
#       print(z)

#print(arr.shape)
#print(arr[:][:][::2])
for x in np.nditer(arr[:,:,::2]):
   print(x)

1
4
3
8
5
9
7
89
10
44
34
83


In [ ]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[8, 9, 88, 90]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7
8
88


In [ ]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


#Joining

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4], [9, 10]])

arr2 = np.array([[5, 6], [7, 8], [11, 23]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 11 23]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2, 3],[ 8, 87, 65]])

arr2 = np.array([[4, 5, 6], [64, 45, 34]])

arr = np.vstack((arr1, arr2))

print(arr)


[[ 1  2  3]
 [ 8 87 65]
 [ 4  5  6]
 [64 45 34]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)
print(arr.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


#Filter

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = (arr % 2 == 0)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr = arr % 3

print(arr)

filter_arr = (arr > 5)


arr = arr / 2

print(arr)

filter_arr = (arr > 2) & (arr < 5) 


newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[1 2 0 1 2 0 1]
[0.5 1.  0.  0.5 1.  0.  0.5]
[False False False False False False False]
[]


In [2]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print('The original array is:') 
print(a)
print('\n') 

print('The transposed array is:') 
print(np.transpose(a))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [30]:
import numpy as np 
a = np.arange(4).reshape(2,2) 

print('The original array:') 
print(a)
print('\n')
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print('The array after applying the swapaxes function:') 
print(np.swapaxes(a, 1, 0))

The original array:
[[0 1]
 [2 3]]


The array after applying the swapaxes function:
[[0 2]
 [1 3]]


In [4]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:')
print(a) 
print('\n')

print('The shape of first array:') 
print(a.shape)
print('\n')  
b = np.resize(a, (3,2)) 

print('Second array:') 
print(b)
print('\n')  

print('The shape of second array:') 
print(b.shape)
print('\n')  
# Observe that first row of a is repeated in b since size is bigger 

print('Resize the second array:') 
b = np.resize(a,(3,3))
print(b)

First array:
[[1 2 3]
 [4 5 6]]


The shape of first array:
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]


The shape of second array:
(3, 2)


Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [31]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print('First array:') 
print(a.shape)
print('\n')  

print('Append elements to array:') 
print(np.append(a, [7,8,9]))
print('\n')  

print('Append elements along axis 0:') 
print(np.append(a, [[7,8,9]],axis = 0)) 
print('\n')  

print('Append elements along axis 1:') 
print(np.append(a, [[5,5,5],[7,8,9]],axis = 1))

First array:
(2, 3)


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [39]:
import numpy as np 
a = np.array([[30,65,70],[80,95,10],[50,90,60]]) 

print('Our array is:') 
print(a )
print('\n')
l = [30,65,70,80,95,10,50,90,60]
l.sort()
print(l)
print(np.sum(a))

print(np.average(a))

print('Applying median() function:') 
print(np.median(a))
print('\n')  

print('Applying median() function along axis 0:') 
print(np.median(a, axis = 0)) 
print('\n') 
 
print('Applying median() function along axis 1:')
print(np.median(a, axis = 1))

Our array is:
[[30 65 70]
 [80 95 10]
 [50 90 60]]


[10, 30, 50, 60, 65, 70, 80, 90, 95]
550
61.111111111111114
Applying median() function:
65.0


Applying median() function along axis 0:
[50. 90. 60.]


Applying median() function along axis 1:
[65. 80. 60.]


In [38]:
print(a )


print('Applying mean() function:') 
print(np.mean(a))
print('\n')  

print('Applying mean() function along axis 0:') 
print(np.mean(a, axis = 0)) 
print('\n')  

print('Applying mean() function along axis 1:')
print(np.mean(a, axis = 1))

print(np.average(a))

[[30 65 70]
 [80 95 10]
 [50 90 60]]
Applying mean() function:
61.111111111111114


Applying mean() function along axis 0:
[53.33333333 83.33333333 46.66666667]


Applying mean() function along axis 1:
[55.         61.66666667 66.66666667]
61.111111111111114


std = sqrt(mean(abs(x - x.mean())**2))


In [10]:
import numpy as np 
print(np.std([1,2,3,4]))

1.118033988749895


var = mean(abs(x - x.mean())**2)*italicized text*

In [11]:
import numpy as np 
print(np.var([1,2,3,4]))

1.25
